### ISSUE TITLE
Errors with non english version

### ISSUE THREAD

**Issue by mathieuchateau** [acasilla/SPFarmInfo#3]
Hello,
Errors are raised when farm is not in english.
Like with this line:
`$configDb = Get-SPDatabase | Where-Object{$_.TypeName -match "Configuration Database"}`

On french SharePoint Farm, TypeName is **Base de données de configuration**

Could match on Configuration keyword, but I guess will not work for Spanish version.

**Comment by joeric2** [comment]
There are a few areas where we have run into similar issues. Raising a work item to look into this. Thanks for the feedback!

**Comment by joeric2** [comment]
We've made a number of check-ins to improve this and look at the actual underlying type, e.g.

Get-SPDatabase  | Where-Object{$_.GetType().FullName -eq "Microsoft.SharePoint.Administration.SPConfigurationDatabase"}

This should be language agnostic and mitigate the issue. I went through and updated several locations that appeared suspect, if you notice any others please let us know.
