### ISSUE TITLE
Get-SPDiagnosticFarmNetworkLatency() / SQLAlias / named instance

### ISSUE THREAD

**Issue by mathieuchateau** [acasilla/SPFarmInfo#6]
Get-SPDiagnosticFarmNetworkLatency() get server name when it's sql alias.
But named  SQL Instance are in server value

like `MYSERVER\INSTANCE01`

Need to change
` $SQLAlias | Add-Member -MemberType NoteProperty -Name "server" -Value $RegVal.Split(',')[1]`
To
`$SQLAlias | Add-Member -MemberType NoteProperty -Name "server" -Value $($RegVal.Split(',')[1] -replace "\\.*","")`

**Comment by joeric2** [comment]
Improvements coming in upcoming release to address this.
